version: '3.8'
services:
  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: ticketredis
    ports:
      - 6379:6379
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ticket
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  data: